// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBytVrwbv4D2pLCgMYrxB-56unop4W6QpE',
    appId: '1:267802124592:web:2a53ff6d5d0e5eae4d28f5',
    messagingSenderId: '267802124592',
    projectId: 'gitalong-c8075',
    authDomain: 'gitalong-c8075.firebaseapp.com',
    storageBucket: 'gitalong-c8075.firebasestorage.app',
    measurementId: 'G-5BZKJKTNKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA230tZ7fhgNx1hgHM2yZBR2Zr1NZ0Dtzc',
    appId: '1:267802124592:android:6e28b610dbc2fb2c4d28f5',
    messagingSenderId: '267802124592',
    projectId: 'gitalong-c8075',
    storageBucket: 'gitalong-c8075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbMQVwYiutRtm5USkpgvDgYEivLX1xIYI',
    appId: '1:267802124592:ios:3c02047f8a1695d24d28f5',
    messagingSenderId: '267802124592',
    projectId: 'gitalong-c8075',
    storageBucket: 'gitalong-c8075.firebasestorage.app',
    iosClientId:
        '267802124592-imp7fos397ehr9rhpjemv2imcjj2b4o8.apps.googleusercontent.com',
    iosBundleId: 'com.gitalong.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbMQVwYiutRtm5USkpgvDgYEivLX1xIYI',
    appId: '1:267802124592:ios:3c02047f8a1695d24d28f5',
    messagingSenderId: '267802124592',
    projectId: 'gitalong-c8075',
    storageBucket: 'gitalong-c8075.firebasestorage.app',
    iosClientId:
        '267802124592-imp7fos397ehr9rhpjemv2imcjj2b4o8.apps.googleusercontent.com',
    iosBundleId: 'com.gitalong.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBytVrwbv4D2pLCgMYrxB-56unop4W6QpE',
    appId: '1:267802124592:web:ed245cf7e89482014d28f5',
    messagingSenderId: '267802124592',
    projectId: 'gitalong-c8075',
    authDomain: 'gitalong-c8075.firebaseapp.com',
    storageBucket: 'gitalong-c8075.firebasestorage.app',
    measurementId: 'G-6B59981K34',
  );
}
